LICENSE
=> Add MPL license

src/lib.rs
The feature flag has been removed.
=> Remove doc_spotlight feature flag

.github/workflows/ci.yml, Cargo.toml, README.md, src/address.rs, src/spawn.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
* update `tokio` to  1.0
* update `flume` to 0.10.1
* rename feature `with-tokio-0_3` to `with-tokio-1`
* rename feature `with-smol-1_1` to `with-smol-1`
=> Update some dependencies

dependabot.yml
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
~~waiting for #26 to be merged~~
=> Setup dependabot

README.md, examples/basic_async_std.rs, examples/basic_smol.rs, examples/basic_tokio.rs, examples/crude_bench.rs, examples/global_spawner_ext.rs, examples/interleaved_messages.rs, src/address.rs, src/context.rs, src/lib.rs, src/manager.rs, src/message_channel.rs, tests/basic.rs
=> Fixup examples

Cargo.toml, benches/throughput.rs
=> Use criterion for benchmarks (correct git history)

.github/workflows/ci.yml, src/address.rs, src/context.rs, src/lib.rs, src/message_channel.rs
It happened multiple times recently that CI did not catch all compile errors in docs or other tests. This patch-set (hopefully) fixes those.
=> Improve CI coverage and fix doc tests

tests/basic.rs
A minor fix that I came across while working on https://github.com/Restioson/xtra/pull/74.
=> Use prime numbers to make clear which additions are being triggered

.github/workflows/ci.yml, Cargo.toml, examples/basic_async_std.rs, examples/basic_wasm_bindgen/src/lib.rs, examples/crude_bench.rs, src/lib.rs, src/send_future.rs
=> Make sure CI covers all examples and benchmarks

.cargo/config.toml, .github/workflows/ci.yml, examples/basic_wasm_bindgen/src/lib.rs, examples/crude_bench.rs, examples/send_interval.rs, src/address.rs, src/broadcast_future.rs, src/context.rs, src/inbox.rs, src/inbox/rx.rs, src/inbox/tx.rs, src/lib.rs, src/message_channel.rs, src/receiver.rs, src/scoped_task.rs, src/send_future.rs, src/tracing.rs, tests/basic.rs
=> Introduce cargo alias for custom formatting

BREAKING-CHANGES.md, examples/crude_bench.rs, src/lib.rs, src/message_channel.rs, tests/basic.rs
Fixes #68.
cc @zesterer What do you think?
=> Introduce `MessageChannel` struct

BREAKING-CHANGES.md, src/address.rs, src/envelope.rs, src/inbox/tx.rs, tests/basic.rs
=> Replace `AddressSink` with `sink::unfold` and `impl Trait`

BREAKING-CHANGES.md, Cargo.toml, README.md, src/context.rs
=> Remove `Context::notify_interval`

BREAKING-CHANGES.md
These traits no longer exist within latest master.
=> Remove outdated changelog entry

.github/workflows/ci.yml, Cargo.toml, README.md, examples/basic_wasm_bindgen/Cargo.toml, src/address.rs, src/context.rs, src/lib.rs, src/message_channel.rs, src/spawn.rs
Fixes #109.
This also makes use of the new `dep:` syntax and thus hides the implicit features generated by optional dependencies.
=> Re-design feature set

BREAKING-CHANGES.md
=> Add missing changelog entry for feature re-design

src/context.rs
=> Annotate TickFuture with must_use

Cargo.toml, src/inbox.rs, src/inbox/waiting_receiver.rs
This works well and saves about 60 LoC.
=> Use `catty` to implement `WaitingReceiver`

src/message_channel.rs
=> Add `MessageChannel::as_either()`

xtra/src/context.rs
=> Document stop_all
