Restioson/xtra

Cargo.toml
README.md
examples/basic_async_std.rs
examples/basic_async_std_async.rs
examples/basic_tokio_async.rs
examples/crude_bench.rs
src/address.rs
src/context.rs
src/envelope.rs
src/lib.rs
src/manager.rs

- Adds `AsyncHandler` trait for handling messages asynchronously
- Adds `do_send_async` and `send_async` for sending messages that should be handled asynchronous
- Added some documentation (unfinished)
- Unresolved question (issue will be open): should we drop the synchronous `Handler` trait altogether to streamline the code and interface? This would mean that synchronous responders would be ~5% slower (according to my benchmarks).

Async Responder

---

BREAKING-CHANGES.md
Cargo.toml
README.md
examples/basic_async_std.rs
examples/basic_async_std_async.rs
examples/basic_tokio.rs
examples/basic_tokio_async.rs
examples/crude_bench.rs
src/address.rs
src/context.rs
src/envelope.rs
src/lib.rs
src/manager.rs
src/message_channel.rs

- Weak addresses that don't prevent the actor from being dropped
- `notify_interval` to notify every x duration
- `notify_after` to notify after x duration
- attach streams to addresses
Todo:

Weak addresses and various notifications

---

BREAKING-CHANGES.md
Cargo.toml
README.md
examples/async_handler.rs
examples/crude_bench.rs
examples/nightly.rs
src/address.rs
src/context.rs
src/envelope.rs
src/lib.rs
src/message_channel.rs

Boxing with async_trait allows this to compile on stable, and perf impacts are negligible (still bottlenecked by the channel impl). `stable` feature added as a **default feature** (breaking change).

Compile on stable

---

Cargo.toml
examples/basic_wasm_bindgen/Cargo.toml
examples/basic_wasm_bindgen/README.md
examples/basic_wasm_bindgen/src/lib.rs
examples/basic_wasm_bindgen/tests/web.rs
src/address.rs
src/context.rs
src/lib.rs
src/manager.rs
src/message_channel.rs

Thanks for xtra! Exactly what I was looking for.
The README states that xtra is runtime agnostic, but I couldn't find an easy way to use it in WASM without the tokio or async-std runtime feature, hence I added the wasm-bindgen support. Hope this is useful.
To run the example `cargo install wasm-pack` is required.
What's missing in this PR are the methods depending on time, like `notify_later`, but I'd be fine to file that as follow-up if the wasm-bindgen feature generally is something you want to support.

wasm-bindgen runtime

---

Cargo.toml
examples/crude_bench.rs
examples/interleaved_messages.rs
src/address.rs
src/context.rs
src/lib.rs
src/manager.rs

This PR adds two methods:
- `Context::handle_while`, allowing the user to handle messages as they arrive while running a given future. This future must be `Unpin` and may not borrow from `self`. It is implemented as a `select` between the two futures, repeating the future waiting for the next message until the first future completes.
- `Context::yield_once`, allowing the user to yield control back to the manager and handle a single message.
This change required some internal refactoring, namely moving handling of messages to the context, but was otherwise very simple to implement and does not introduce much technical debt.
To do:
Potentially closes #13

`Context::handle_while` and `Context::yield_once` for interleaving messages

---

examples/message_stealing.rs
src/address.rs
src/lib.rs
src/message_channel.rs
src/refcount.rs
tests/basic.rs

* Take `Actor` by value in `stopped` lifecycle method (API breaking, but more permissive)
* Implement `PartialEq + Eq + PartialOrd + Ord + Hash` on `Address` by pointer identity
(uses the `ref_counter`, because `flume::Sender` doesn't expose `Arc` or pointer)
---
real find and replace hours

Quality of my life

---

src/address.rs

Prevents misuses of the API, e.g.
`address.send()` without calling `.await` on it.

Annotate SendFuture with #[must_use] attribute

---

src/address.rs

Prevents misuses of the API, e.g.
`address.do_send_async()` without calling `.await` on it.
Sorry, I missed the second use-case - ideally I would have sent a single PR!

Annotate DoSendFuture with #[must_use] attribute

---

src/address.rs
src/context.rs
src/envelope.rs
src/manager.rs
src/sink.rs

Trait bounds that are specified on structs ripple easily through
entire codebases.
In this particular case, requiring `Actor` for an `Address` is
unnecessary and makes it harder to hold on `Address` to an actor
that is represented by a type parameter.

Remove `Actor` trait bounds from structs

---

src/message_channel.rs

This way the compiler will remind us to `await` this kind of future.
It's the same QoL improvement which was introduced for `Address` in https://github.com/Restioson/xtra/pull/39.

Mark message_channel::SendFuture as must_use

---

src/lib.rs
src/tracing.rs

This PR fixes some minor formatting issues that `rustfmt` is complaining about and causes problems with CI.
It also adds a missing feature flag to `lib.rs`. Otherwise `master` won't compile when tracing isn't enabled.

Fixes formatting and adds missing feature flag

---

src/spawn.rs

In case no features are enabled, these 3 imports
are flagged as unused code.
Add the import line to each individual module to
avoid this.

Fix dead code warnings

---

examples/basic_async_std.rs
examples/basic_smol.rs
examples/basic_tokio.rs
examples/basic_wasm_bindgen/src/lib.rs
examples/crude_bench.rs
examples/global_spawner_ext.rs
examples/interleaved_messages.rs
examples/message_stealing.rs
src/address.rs
src/lib.rs
src/message_channel.rs
tests/basic.rs

This allows downstream users to avoid declaring this dependency
separately.

Re-export `async_trait` from prelude

---

examples/basic_smol.rs
examples/global_spawner_ext.rs
examples/interleaved_messages.rs
examples/message_stealing.rs
src/address.rs
src/context.rs
src/lib.rs
src/manager.rs
src/message_channel.rs
src/spawn.rs
tests/basic.rs

This is useful for building supervisor patterns where the supervisor can learn, why a certain actor stopped operating. You can find our current implementation here: https://github.com/itchysats/itchysats/blob/feature/better-supervisor/xtras/src/supervisor.rs
A couple of design decisions went into this patch:
1. I chose to be Rust-stable compatible and thus, we don't have associated type-defaults. Once they become stable, we could use them.
2. I chose to require `Actor::stopped` to be implemented by every actor. This is a slight ergonomic hit but I believe it is the overall best trade-off.
a. A developer SHOULD think about why its actor is stopping.
b. If `Stop` is `()`, the method body can be empty and usually collapses into one line, hence not that big a deal really.
c. If `Stop` ever …

Introduce `Actor::Stop`

---

examples/basic_smol.rs
examples/basic_tokio.rs
examples/global_spawner_ext.rs
examples/interleaved_messages.rs
examples/message_stealing.rs
src/address.rs
src/context.rs
src/envelope.rs
src/lib.rs
src/message_channel.rs
src/sink.rs
src/tracing.rs
tests/basic.rs

We have been working with `xtra` for a while now and something that came up repeatedly is the `Message` trait. In particular, I would like to discuss the idea of removing it.
Requiring the trait to be implemented in order to declare that an actor is able to handle a message hurts ergonomics as you try to modularise a codebase that heavily depends on `xtra`. Traits can only be implemented once and the orphan rule enforces that this happens where the struct is declared.
This PR presents a Proof-of-Concept for removing the `Message` trait in favor of an associated type on the `Handler` trait. Unless I missed something, all current functionality is retained. What do you think?

Remove `Message` trait

---

BREAKING-CHANGES.md
Cargo.toml
benches/throughput.rs
examples/backpressure.rs
examples/message_stealing.rs
src/address.rs
src/context.rs
src/lib.rs
src/message_channel.rs
src/receiver.rs
src/send_future.rs
tests/basic.rs

This PR presents a unified API for sending messages to actors. We now only have a single `send` function on both `Address` and `MessageChannel` and we return the same `SendFuture` type in both cases.
The `SendFuture` type has a single, publicly accessible function called `recv_async` which allows users to flip the behaviour of `SendFuture` from synchronously awaiting the handler's result to returning a `Receiver` that can be awaited separately.
This allows users to _queue_ messages into an actor's mailbox without awaiting the result. As part of merging the two existing `SendFuture` types, we now also provide a consistent "backpressure" story: A `SendFuture` that is flipped to receiving the result asynchronously will only complete once the message has been successfully queued into the …

Unify the `send` API on `Address` and `MessageChannel`

---

.github/workflows/ci.yml
Cargo.toml
README.md
examples/basic_wasm_bindgen/Cargo.toml

Changes xtra's MSRV to 1.56, enables edition 2021, and make actions use minimal-versions. 
This was required for edition 2021, as it was the first stable version with edition 2021 enabled. 
The main effect this had is the different feature resolver needed one feature to be added explicitly to futures-util.
There are two reasons for making Actions use `minimal-versions`:
1. Unfortunately, since the CI is tested on 1.56 too *without* Cargo.lock being committed, the latest dependencies are always used. This includes updating to those beyond the MSRV of the root crate (xtra) - see https://github.com/rust-lang/cargo/issues/9930. This lead to some CI failures which did not reflect actual MSRV issues with xtra, since the dependencies updated beyond xtra's MSRV had releases allowed by xtra that …

Minimal 2021 edition update, MSRV -> 1.56, GHA update

---

Cargo.toml
README.md
examples/scoped_actor_task.rs
src/address.rs
src/drop_notice.rs
src/lib.rs
src/refcount.rs
src/scoped_task.rs
tests/basic.rs

This is a concept for an API which allows you to spawn tasks that will never outlive the actor. It might be better suited to an extension crate at a later date.
CC @klochowicz

Scoped task spawning

---

tests/basic.rs

`BroadcastHello` is confusing because it is also used to test
non-broadcast functions and broadcasting itself doesn't require
any specific messages (other than having their `Return` set to `()`).

Rename `BroadcastHello` to `PrintHello`

---

src/context.rs
src/envelope.rs
src/inbox/tx.rs

This PR adds a function which returns the span of the inner message handler, so that it can be recorded and logged to by a custom event loop.
```rust
pub async fn run(mut self, mut actor: A) -> A::Stop {
loop {
let msg = self.ctx.next_message().await;
let (span, fut) = self.ctx.tick_instrumented(msg, &mut actor);
match timeout(self.timeout, fut).await {
Ok(ControlFlow::Continue(())) => (),
Ok(ControlFlow::Break(())) => break actor.stopped().await,
Err(_elapsed) => {
if let Some(span) = span {
let _entered = span.enter();
let timeout_seconds = self.timeout.as_secs();
span.record("interrupted", &"timed_out");
tracing::warn!(%timeout_seconds, "Handler execution timed out");
}
}
}
}
}
```
Without this change, there would be no way to log that the message handler timed out to any child span of …

Add TickFuture and TickFuture::get_or_create

---

src/context.rs

These annotations generate a warning when compiling the docs with
a nightly compiler. We also do now have a separate example in the
documentation of this function so embedding the other example is
not necessary.

Remove legacy doc attributes from `Context::join`

---

src/address.rs
src/broadcast_future.rs
src/inbox.rs
src/inbox/rx.rs
src/inbox/tx.rs
src/message_channel.rs
src/send_future.rs

As part of trying to come up with an alternative to https://github.com/Restioson/xtra/pull/120, I started to move a bit of code around and ended up with this patch set!
Each commit in its own builds and has passing tests and I was careful to try and not alter any behaviour. In other words, this is a pure refactoring.
The goal was as follows:
- Have `Chan` house the core channel implementation with descriptive function names for key operations
- Have `Sender` and `Receiver` be thin layers on top that combine `Chan` with reference counting and provide a `Future`-based APIs for sending and receiving
I can extract some of these commits into individual PRs if you want. The diff will be quite hard to follow once it is squashed.

Move channel logic into `Chan`

---

Cargo.toml
README.md
src/address.rs
src/message_channel.rs

Not every user may need the `sink` feature and we can minimise
our dependency tree in those cases.

Introduce optional `sink` feature

---

src/context.rs
src/inbox/rx.rs
tests/basic.rs

Remove `ReceiveFuture::cancel` in favor of cancellation-safety docs

---

src/address.rs
src/broadcast_future.rs
src/envelope.rs
src/inbox.rs
src/inbox/rx.rs
src/inbox/tx.rs
src/message_channel.rs

Previously, we only stored the priority of broadcast messages in
the envelope. For regular messages, the priority was stored
outside in a wrapper struct.
This disparity is hard to understand as there is no apparent reason
why the priority could not be stored in the message envelope.
With this patch, we move the priority into the message envelope
and also expose a `set_priority` function for each envelope type
which allows us to consolidate the way we set priority from the
`SendFuture`.

Always store message priority in envelope

---

src/broadcast_future.rs
src/envelope.rs
src/inbox.rs
src/inbox/tx.rs
src/send_future.rs

An envelope knows which message it is carrying, no need to pass
it in.

Don't pass message name into envelope

---

src/envelope.rs
tests/instrumentation.rs

This makes sure that if the xtra_actor_request is disabled, the other spans and child-spans of xtra_message_handler will be children of the would-be parent of xtra_actor_request, rather than being parentless, top-level spans.

Use or_current when creating spans

---

src/context.rs
src/inbox.rs
src/inbox/rx.rs
src/inbox/waiting_receiver.rs

We never use weak references to mailboxes and don't expose a way for the user to construct one. Hence, the concept of generic reference counting is not useful here and only adds complexity.

Remove generic ref-counting from `Receiver`

---

src/address.rs
src/context.rs
src/inbox.rs
src/inbox/tx.rs
src/send_future.rs

Essentially, `Sender` is a smart-pointer to `Chan` with custom reference
counting logic and thus it makes sense for it to implement `Deref`.
Most of the functionality accessed by other modules lives on `Chan`.

Have `Sender` deref to `Chan`

---

src/inbox.rs

Previously, we first checked whether the corresponding queue WILL
have space if we now pop a message.
This is functionally equivalent to _trying_ to pop a message, exiting
early if we can't (using `?`) and then adding another message to the
queue if we now have space.
Checking for space is equivalent to the queue not being full and we
already have helper functions for this.

Simplify control-flow in `ChanInner::pop_` functions

---

tests/instrumentation.rs

The elements in the file are now ordered by priority (tests come first) and the implementation of the tracing harness is tidied up to reduce duplication between the tests.

Refactor instrumentation tests

---

Cargo.toml
README.md
macros-test/Cargo.toml
macros-test/README.md
macros-test/src/lib.rs
macros-test/tests/pass/basic.rs
macros-test/tests/pass/generics.rs
macros-test/tests/ui.rs
macros/Cargo.toml
macros/src/lib.rs
src/lib.rs

Add an `Actor` custom derive macro

---

.cargo/config.toml
examples/basic_wasm_bindgen/src/lib.rs
examples/crude_bench.rs
src/lib.rs

Most of our codebase seems to be formatted this way, we can enforce
this with a rustfmt setting.

Enforce grouping of imports per module

---

Cargo.toml
examples/scoped_actor_task.rs

Because of an unknown feature, this example was not compiled as
part of our CI run and we missed it while moving to the new spawn
API.

Fix `scoped_actor_task` example

---

src/context.rs
src/envelope.rs
src/instrumentation.rs
src/instrumentation/stub.rs
src/instrumentation/tracing.rs
src/lib.rs

By splitting things into modules with identical APIs, we can remove a lot of `cfg(feature)` attributes.

Simplify conditional code around instrumentation feature

---

tests/basic.rs

Previously, xtra's Actor had different behaviour depending on whether the last `Address` was dropped, `Context::stop` was called or `Context::stop_self` was called.
With the removal of `Actor::stopping` and the simplification of the event loop, these behaviours have been unified. Prior to this patch, the tests written for these cases were a bit outdated.
We simplify these tests and split them into individual ones.

Rework tests around drop behaviour of actors

---

src/address.rs
src/chan/ptr.rs
src/message_channel.rs
tests/basic.rs

This patch proposes a slightly more user-friendly debug output of addresses and message channels. Instead of rx/tx terminology, we use addresses and mailboxes.

Remove rx/tx terminology from Debug output

---

.github/workflows/ci.yml

`Swatinem/rust-cache` considers the lockfile it finds in the repo for its cache key. If we update it _after_ restoring the cache, the cache key will never match exactly.

Update lockfile before computing cache key

---

BREAKING-CHANGES.md
README.md

Resolves: #186.
Resolves: #200.

Tidy-up README and CHANGELOG

---

xtra/Cargo.toml

This PR adds an explicit `macros` feature to the manifest.
Typically one will look at the manifest `[features]` section to quickly identify which features are available (especially if not documented in the top-level crate docs). Searching for implicit features via optional dependencies leaves something to be desired.

chore: add explicit macros feature to manifest

---

README.md

The old link for the examples folder in the README needed to be fixed. This fix updates it

Fix for the examples link in the Readme.md

---

.github/workflows/ci.yml
BREAKING-CHANGES.md
Cargo.lock
README.md
macros-test/tests/pass/basic.rs
macros-test/tests/pass/generics.rs
macros/src/lib.rs
xtra/Cargo.toml
xtra/benches/throughput.rs
xtra/examples/address_sink.rs
xtra/examples/backpressure.rs
xtra/examples/basic_async_std.rs
xtra/examples/basic_smol.rs
xtra/examples/basic_tokio.rs
xtra/examples/basic_wasm_bindgen/Cargo.toml
xtra/examples/basic_wasm_bindgen/src/lib.rs
xtra/examples/crude_bench.rs
xtra/examples/custom_event_loop.rs
xtra/examples/interleaved_messages.rs
xtra/examples/manual_actor_impl.rs
xtra/examples/message_stealing_multiple_actors.rs
xtra/examples/scoped_actor_task.rs
xtra/examples/send_interval.rs
xtra/src/address.rs
xtra/src/chan/ptr.rs
xtra/src/dispatch_future.rs
xtra/src/lib.rs
xtra/src/message_channel.rs
xtra/tests/basic.rs
xtra/tests/instrumentation.rs

Remove `async_trait` macro in favor of AFIT & RPITIT

---

xtra/src/lib.rs

This PR updates the doctests on `select` and `join` functions to get rid of the deprecated `with-smol-1` feature gate and uses the new `smol` feature instead.
Closes #214 
Should `smol` be added into `[dev-dependencies]` so this sort of thing isn't possible? Doctests should ideally run fully without having to enable a feature.

fix: update doctests to use smol feature

---

xtra/examples/crude_bench.rs

We had a warning from beta clippy on the main branch. This should fix that.
Alternatively we may want to use it and throw away the value with `black_box`, but I'm not sure if this is stable yet

Fix CI warning

---

xtra/examples/crude_bench.rs

It appears that a recent update to Rust changed / improved the dead-code detection which is now triggering on this unused code.

chore: remove dead-code from benchmark

---

xtra/src/message_channel.rs

This adds the `Hash` trait to `MessageChannel`. I need this in my project to use a `MessageChannel` as a key in a `HashMap` (as actor types are generally unknown for my use case). Pairs with the existing `PartialEq`.

feat: implement Hash for MessageChannel
